"""update job id column

Revision ID: 044e2fc6d729
Revises: 701821449741
Create Date: 2024-10-24 13:31:59.377647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '044e2fc6d729'
down_revision: Union[str, None] = '701821449741'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_table', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_index('ix_job_table_job_id', table_name='job_table')
    op.create_index(op.f('ix_job_table_id'), 'job_table', ['id'], unique=False)
    op.create_foreign_key(None, 'job_table', 'user_table', ['user_id'], ['id'])
    op.drop_column('job_table', 'job_id')
    op.create_foreign_key(None, 'password_reset_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_table', type_='foreignkey')
    op.add_column('job_table', sa.Column('job_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'job_table', type_='foreignkey')
    op.drop_index(op.f('ix_job_table_id'), table_name='job_table')
    op.create_index('ix_job_table_job_id', 'job_table', ['job_id'], unique=False)
    op.drop_column('job_table', 'id')
    # ### end Alembic commands ###
