"""Add columns for teacher in user table

Revision ID: 0793c1abbf76
Revises: 4ff71a3fe784
Create Date: 2024-10-23 15:07:19.296555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0793c1abbf76'
down_revision: Union[str, None] = '4ff71a3fe784'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'password_reset_table', 'user_table', ['user_id'], ['id'])
    op.add_column('user_table', sa.Column('cv', sa.String(length=255), nullable=True))
    op.add_column('user_table', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('user_table', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('user_table', sa.Column('approved', sa.Boolean(), nullable=True))
    op.add_column('user_table', sa.Column('experience', sa.Float(), nullable=True))
    op.add_column('user_table', sa.Column('work_at_place', sa.String(length=100), nullable=True))
    op.add_column('user_table', sa.Column('education', sa.String(length=100), nullable=True))
    op.add_column('user_table', sa.Column('degree_year', sa.Integer(), nullable=True))
    op.add_column('user_table', sa.Column('skills', sa.String(length=255), nullable=True))
    op.add_column('user_table', sa.Column('hobby', sa.String(length=255), nullable=True))
    op.add_column('user_table', sa.Column('gender', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'gender')
    op.drop_column('user_table', 'hobby')
    op.drop_column('user_table', 'skills')
    op.drop_column('user_table', 'degree_year')
    op.drop_column('user_table', 'education')
    op.drop_column('user_table', 'work_at_place')
    op.drop_column('user_table', 'experience')
    op.drop_column('user_table', 'approved')
    op.drop_column('user_table', 'age')
    op.drop_column('user_table', 'date_of_birth')
    op.drop_column('user_table', 'cv')
    op.drop_constraint(None, 'password_reset_table', type_='foreignkey')
    # ### end Alembic commands ###
