"""Create job table

Revision ID: 0a0701730458
Revises: c37ffec22dc0
Create Date: 2024-10-24 12:42:53.686435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0701730458'
down_revision: Union[str, None] = 'c37ffec22dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jobe_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_table_id'), 'job_table', ['id'], unique=False)
    op.create_index(op.f('ix_job_table_jobe_name'), 'job_table', ['jobe_name'], unique=True)
    op.create_foreign_key(None, 'password_reset_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_table', type_='foreignkey')
    op.drop_index(op.f('ix_job_table_jobe_name'), table_name='job_table')
    op.drop_index(op.f('ix_job_table_id'), table_name='job_table')
    op.drop_table('job_table')
    # ### end Alembic commands ###
