"""Create Job table and add one-to-one relationship with User

Revision ID: 6684a38a3395
Revises: 7d81de471452
Create Date: 2024-10-24 12:47:26.143473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6684a38a3395'
down_revision: Union[str, None] = '7d81de471452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_table', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'job_table', 'user_table', ['user_id'], ['id'])
    op.create_foreign_key(None, 'password_reset_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_table', type_='foreignkey')
    op.drop_constraint(None, 'job_table', type_='foreignkey')
    op.drop_column('job_table', 'user_id')
    # ### end Alembic commands ###
