"""create child table

Revision ID: 6ff36db4a770
Revises: 9d263283a1cb
Create Date: 2024-10-25 14:54:30.287307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff36db4a770'
down_revision: Union[str, None] = '9d263283a1cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('guardian_phone', sa.String(length=50), nullable=True),
    sa.Column('guardian_email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=225), nullable=True),
    sa.Column('child_class', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('birth_mark', sa.String(length=225), nullable=True),
    sa.Column('health_issue', sa.String(length=225), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('hafiz', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guardian_email')
    )
    op.create_index(op.f('ix_child_table_id'), 'child_table', ['id'], unique=False)
    op.create_foreign_key(None, 'job_table', 'user_table', ['user_id'], ['id'])
    op.create_foreign_key(None, 'password_reset_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_table', type_='foreignkey')
    op.drop_constraint(None, 'job_table', type_='foreignkey')
    op.drop_index(op.f('ix_child_table_id'), table_name='child_table')
    op.drop_table('child_table')
    # ### end Alembic commands ###
