"""update columns type for job table

Revision ID: 701821449741
Revises: 6684a38a3395
Create Date: 2024-10-24 13:29:32.337051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701821449741'
down_revision: Union[str, None] = '6684a38a3395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_table_job_name', table_name='job_table')
    op.create_index(op.f('ix_job_table_job_name'), 'job_table', ['job_name'], unique=False)
    op.create_foreign_key(None, 'job_table', 'user_table', ['user_id'], ['id'])
    op.create_foreign_key(None, 'password_reset_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_table', type_='foreignkey')
    op.drop_constraint(None, 'job_table', type_='foreignkey')
    op.drop_index(op.f('ix_job_table_job_name'), table_name='job_table')
    op.create_index('ix_job_table_job_name', 'job_table', ['job_name'], unique=True)
    # ### end Alembic commands ###
