"""Add user-password_reset relationship

Revision ID: 879b7dcd5d57
Revises: 0c8bce92c527
Create Date: 2024-10-22 16:13:47.959693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879b7dcd5d57'
down_revision: Union[str, None] = '0c8bce92c527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_reset_table', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'password_reset_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_table', type_='foreignkey')
    op.drop_column('password_reset_table', 'user_id')
    # ### end Alembic commands ###
