"""Add token_expiry column in user table

Revision ID: 9abd4168303b
Revises: 879b7dcd5d57
Create Date: 2024-10-22 16:17:51.118633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9abd4168303b'
down_revision: Union[str, None] = '879b7dcd5d57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'password_reset_table', 'user_table', ['user_id'], ['id'])
    op.add_column('user_table', sa.Column('token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_table', 'token_expiry')
    op.drop_constraint(None, 'password_reset_table', type_='foreignkey')
    # ### end Alembic commands ###
