"""establish relationship between child and user table

Revision ID: c88c131af81c
Revises: 6ff36db4a770
Create Date: 2024-10-28 12:10:14.867451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88c131af81c'
down_revision: Union[str, None] = '6ff36db4a770'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('child_table', sa.Column('parent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'child_table', 'user_table', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'job_table', 'user_table', ['user_id'], ['id'])
    op.create_foreign_key(None, 'password_reset_table', 'user_table', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'password_reset_table', type_='foreignkey')
    op.drop_constraint(None, 'job_table', type_='foreignkey')
    op.drop_constraint(None, 'child_table', type_='foreignkey')
    op.drop_column('child_table', 'parent_id')
    # ### end Alembic commands ###
