"""remove column token expiry from user table

Revision ID: e9ae26e6cc13
Revises: 9abd4168303b
Create Date: 2024-10-23 11:44:46.778482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e9ae26e6cc13'
down_revision: Union[str, None] = '9abd4168303b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'password_reset_table', 'user_table', ['user_id'], ['id'])
    op.drop_column('user_table', 'token_expiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_table', sa.Column('token_expiry', mysql.DATETIME(), nullable=True))
    op.drop_constraint(None, 'password_reset_table', type_='foreignkey')
    # ### end Alembic commands ###
